name = "gitcord-forum"
main = "./build/index.js"
workers_dev = true
compatibility_date = "2022-11-30"

kv_namespaces = [{ binding = "DB", id = "cf4ceb8a79e94a8587f4ef71a07ae6a2" }]

[build]
command = "npm run build"

[vars]
# Sensitive data should be stored in the worker itself as an encrypted value... in other terms: NOT IN THIS FILE!
# Method 1 is to use the `wrangler` command: `wrangler secret put <key>` where key is the environment variable name
# Method 2 is to put them in through the workers dashboard
#
# Sensitive environment variables:
# - GITHUB_WEBHOOK_SECRET - your secret for webhooks
# - DISCORD_WEBHOOK       - your discord webhook link (needs to be in a forum channel!)
# All sensitive variables get a default value of "" just so the worker doesn't crash

IGNORED_USERS = "renovate[bot],github-actions[bot],cloudflare-pages[bot]"
FALLBACK_URL = "https://github.com/biaw/gitcord-forum" # Fallback URL for when a user types the worker address
